plugins {
    id 'com.android.application'
}
android {
    namespace "com.car.floatpanel"
    compileSdk 33
    defaultConfig {
        applicationId "com.car.floatpanel"
        minSdk 26
        targetSdk 26
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
dependencies {
    implementation 'com.amap.api:maps:9.7.0'
    implementation 'com.github.felHR85:UsbSerial:6.1.0'
}
